apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadmfdo7677-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadmfdo7677-tenant-component
    app.kubernetes.io/part-of: loadmfdo7677-tenant-app
  name: loadmfdo7677-tenant-component
  namespace: loadmfdo7677-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadmfdo7677-tenant-component
    weight: null
status: {}
